package Immobiliaris.Progetto_Rooftop.Model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity mapping the `faq` table.
 * Represents a Frequently Asked Question (FAQ) with category, question, answer, and display order.
 */
@Entity
@Table(name = "faq")
public class Faq {

    /**
     * Primary key of the FAQ, generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_faq")
    private int id_faq;

    /**
     * Category of the FAQ, stored as a string enum value.
     * Must match one of the values in CategoriaFaq.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "categoria", nullable = false, length = 20)
    private CategoriaFaq categoria;

    /**
     * The question text.
     */
    @Column(name = "domanda", nullable = false, columnDefinition = "TEXT")
    private String domanda;

    /**
     * The answer text.
     */
    @Column(name = "risposta", nullable = false, columnDefinition = "TEXT")
    private String risposta;

    /**
     * Display order used for sorting in listings.
     */
    @Column(name = "ordine")
    private int ordine = 0;

    /**
     * Default constructor required by JPA.
     */
    public Faq() {}

    /**
     * Convenience constructor to initialize all fields.
     */
    public Faq(CategoriaFaq categoria, String domanda, String risposta, int ordine) {
        this.categoria = categoria;
        this.domanda = domanda;
        this.risposta = risposta;
        this.ordine = ordine;
    }

    /**
     * Returns the FAQ identifier.
     */
    public int getId_faq() {
        return id_faq;
    }

    /**
     * Sets the FAQ identifier.
     */
    public void setId_faq(int id_faq) {
        this.id_faq = id_faq;
    }

    /**
     * Returns the category.
     */
    public CategoriaFaq getCategoria() {
        return categoria;
    }

    /**
     * Sets the category.
     */
    public void setCategoria(CategoriaFaq categoria) {
        this.categoria = categoria;
    }

    /**
     * Returns the question text.
     */
    public String getDomanda() {
        return domanda;
    }

    /**
     * Sets the question text.
     */
    public void setDomanda(String domanda) {
        this.domanda = domanda;
    }

    /**
     * Returns the answer text.
     */
    public String getRisposta() {
        return risposta;
    }

    /**
     * Sets the answer text.
     */
    public void setRisposta(String risposta) {
        this.risposta = risposta;
    }

    /**
     * Returns the display order.
     */
    public int getOrdine() {
        return ordine;
    }

    /**
     * Sets the display order.
     */
    public void setOrdine(int ordine) {
        this.ordine = ordine;
    }
}