package Immobiliaris.Progetto_Rooftop.Model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * JPA entity mapping the `recensioni` table.
 * Represents a review left by a client for an agent and optionally an immobile.
 */
@Entity
@Table(name = "recensioni")
public class Recensione {

    /** Primary key of the review, generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id_recensione")
    private int id_recensione;

    /** Agent who receives the review (FK to utenti.id_utente). */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id_agente", nullable = false)
    private Utente agente;

    /** Optional immobile associated to the review (FK to immobili.id_immobile). */
    @Column(name = "id_immobile")
    private Integer id_immobile;

    /** Client display name shown with the review. */
    @Column(name = "nome_cliente", length = 100)
    private String nome_cliente;

    /** Rating from 1 to 5. */
    @Column(name = "rating", nullable = false)
    private int rating;

    /** Optional title of the review. */
    @Column(name = "titolo", length = 255)
    private String titolo;

    /** Review body text. */
    @Column(name = "commento", nullable = false, columnDefinition = "TEXT")
    private String commento;

    /** Mark whether the review has been verified by staff. */
    @Column(name = "verificata")
    private boolean verificata = false;

    /** Timestamp when the review was created. */
    @Column(name = "created_at", updatable = false)
    private LocalDateTime created_at;

    /** Set creation timestamp if not provided. */
    @PrePersist
    protected void onCreate() {
        if (created_at == null) {
            created_at = LocalDateTime.now();
        }
    }

    public Recensione() {}

    public Recensione(Utente agente, Integer id_immobile, String nome_cliente, int rating, String titolo, String commento, boolean verificata) {
        this.agente = agente;
        this.id_immobile = id_immobile;
        this.nome_cliente = nome_cliente;
        this.rating = rating;
        this.titolo = titolo;
        this.commento = commento;
        this.verificata = verificata;
    }

    public int getId_recensione() { return id_recensione; }
    public void setId_recensione(int id_recensione) { this.id_recensione = id_recensione; }

    public Utente getAgente() { return agente; }
    public void setAgente(Utente agente) { this.agente = agente; }

    public Integer getId_immobile() { return id_immobile; }
    public void setId_immobile(Integer id_immobile) { this.id_immobile = id_immobile; }

    public String getNome_cliente() { return nome_cliente; }
    public void setNome_cliente(String nome_cliente) { this.nome_cliente = nome_cliente; }

    public int getRating() { return rating; }
    public void setRating(int rating) { this.rating = rating; }

    public String getTitolo() { return titolo; }
    public void setTitolo(String titolo) { this.titolo = titolo; }

    public String getCommento() { return commento; }
    public void setCommento(String commento) { this.commento = commento; }

    public boolean isVerificata() { return verificata; }
    public void setVerificata(boolean verificata) { this.verificata = verificata; }

    public LocalDateTime getCreated_at() { return created_at; }
    public void setCreated_at(LocalDateTime created_at) { this.created_at = created_at; }
}